name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser'
        required: false
        default: 'chromium'
        type: choice
        options:
        - chromium
        - firefox
        - safari
      spec:
        description: 'Path to the spec file'
        required: false
        default: './tests/*.ts'
        type: string
      smoke:
        description: 'Run smoke tests only'
        required: false
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Cache modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: |
          if [[ "${{ inputs.smoke }}" == "true" ]]; then
            echo "Running smoke tests..."
            npx playwright test --project=${{ inputs.browser }} --grep @smoke
          elif [[ "${{ inputs.smoke }}" == "false" ]]; then
            echo "Running all tests matching: ${{ inputs.spec }}"
            npx playwright test ${{ inputs.spec }} --project=${{ inputs.browser }}
          fi
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30