name: UI Tests for dummy website
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Add node
        uses: actions/setup-node@v4
      - name: Install dependancies
        run: npm ci
      - name: Browser Chromium
        run: npx playwright install chromium --with-deps
      - name: Run playwright test
        run: npm run <file name>
